compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: clang@10.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@11.1.0
      target: x86_64
