# Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and
# Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        # -Wno-int-conversion flag needed for building HDF5
        # cflags: -Wno-int-conversion
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.4.3/llvm/bin/amdclang
        cxx: /opt/rocm-5.4.3/llvm/bin/amdclang++
        f77: /opt/rocm-5.4.3/llvm/bin/amdflang
        fc: /opt/rocm-5.4.3/llvm/bin/amdflang
      spec: clang@15.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      # -Wno-int-conversion flag needed for building HDF5
      # -O1 flag necessary for bypassing HIP out of memory error
      flags:
        # cflags: -Wno-int-conversion -O1
        # cflags: -O1
        # cxxflags: -O1
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.5.1/llvm/bin/amdclang
        cxx: /opt/rocm-5.5.1/llvm/bin/amdclang++
        f77: /opt/rocm-5.5.1/llvm/bin/amdflang
        fc: /opt/rocm-5.5.1/llvm/bin/amdflang
      spec: clang@16.0.0
      target: x86_64
  - compiler:
      # spec: cce@15.0.1
      spec: clang@15.0.1
      paths:
        cc: /usr/tce/packages/cce-tce/cce-15.0.1/bin/craycc
        cxx: /usr/tce/packages/cce-tce/cce-15.0.1/bin/crayCC
        f77: /usr/tce/packages/cce-tce/cce-15.0.1/bin/crayftn
        fc: /usr/tce/packages/cce-tce/cce-15.0.1/bin/crayftn
      # -O1 flag necessary for bypassing HIP compiler errors
      # flags: {}
      flags:
      #   # -Wno-int-conversion flag needed for building HDF5
      #   # cflags: -Wno-int-conversion
        # cflags: -O1
        # cxxflags: -O1
        fflags: -ef
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  packages:
    all:
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [cray-mpich]

    hip:
      buildable: false
      externals:
      - spec: hip@5.4.3
        prefix: /opt/rocm-5.4.3/hip
      - spec: hip@5.5.1
        prefix: /opt/rocm-5.5.1/hip

    llvm-amdgpu:
      buildable: false
      externals:
      - spec: llvm-amdgpu@5.4.3
        prefix: /opt/rocm-5.4.3/llvm
      - spec: llvm-amdgpu@5.5.1
        prefix: /opt/rocm-5.5.1/llvm

    hsa-rocr-dev:
      buildable: false
      externals:
      - spec: hsa-rocr-dev@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: hsa-rocr-dev@5.5.1
        prefix: /opt/rocm-5.5.1/

    rocblas:
      buildable: false
      externals:
      - spec: rocblas@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocblas@5.5.1
        prefix: /opt/rocm-5.5.1/

    rocminfo:
      buildable: false
      externals:
      - spec: rocminfo@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocminfo@5.5.1
        prefix: /opt/rocm-5.5.1/

    rocprim:
      buildable: false
      externals:
      - spec: rocprim@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocprim@5.5.1
        prefix: /opt/rocm-5.5.1/

    rocm-device-libs:
      buildable: false
      externals:
      - spec: rocm-device-libs@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocm-device-libs@5.5.1
        prefix: /opt/rocm-5.5.1/

    # Lock down which MPI we are using
    mpi:
      buildable: false
    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.25%clang@15.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.4.3/
      - spec: cray-mpich@8.1.25%clang@16.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.5.1/
      - spec: cray-mpich@8.1.25%clang@15.0.1+slurm
      # - spec: cray-mpich@8.1.25%cce@15.0.1+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.4.3-cce-15.0.1/
        # prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.25-cce-15.0.1-magic/

    # blas is a bit more complicated because its a virtual package so fake it with
    # the following per spack docs
    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.6.1
        prefix: /usr

    # System level packages to not build
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      buildable: false
      externals:
      - spec: automake@1.13.4
        prefix: /usr
    binutils:
      buildable: false
      externals:
      - spec: binutils@2.27
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.61.1
        prefix: /usr
    cmake:
      version: [3.24.2]
      buildable: false
      externals:
      - spec: cmake@3.24.2
        prefix: /usr/tce
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.3
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.176
        prefix: /usr
    epoxy:
      buildable: false
      externals:
      - spec: epoxy@1.5.2
        prefix: /usr
    findutils:
      buildable: false
      externals:
      - spec: findutils@4.5.11
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    ghostscript:
      buildable: false
      externals:
      - spec: ghostscript@9.25
        prefix: /usr
    gmake:
      buildable: false
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
    groff:
      buildable: false
      externals:
      - spec: groff@1.22.2
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.30.1
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.2
        prefix: /usr
    libunwind:
      buildable: false
      externals:
      - spec: libunwind@8.0.1
        prefix: /usr
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.20.4
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.16
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.16.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.27.1
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@6.2
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.26
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.7
        prefix: /usr

    # External dependencies for SCR
    lsf:
      buildable: False
      externals:
      - spec: lsf@10.1
        prefix: /opt/ibm/spectrumcomputing/lsf/10.1
    slurm:
      buildable: false
      externals:
      - spec: slurm@20
        prefix: /usr
    libyogrt:
      externals:
      - spec: libyogrt@1.24 scheduler=lsf
        prefix: /usr
      - spec: libyogrt@1.24 scheduler=slurm
        prefix: /usr
    pdsh:
      buildable: false
      externals:
      - spec: pdsh@2.33
        prefix: /usr

    # Globally lock version of third party libraries
    camp:
      require: "@2022.10.1"
    conduit:
      require: "@0.8.8~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    hypre:
      version: [2.24.0]
      variants: ~fortran
    mfem:
      require: "@4.5.2"
    raja:
      require: "@2022.10.5~shared~examples~exercises"
    scr:
      require: "@3.0.1~shared~tests~examples"
    umpire:
      require: "@2022.10.0~shared~examples"
