compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: gcc@8.3.1.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: gcc@8.3.1.2
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      # Fix for "undefined reference to `_gfortran_transfer_integer_write'"
      ldlibs: -lgfortran
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang
      cxx: /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: clang@10.0.1.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      # Fix for "undefined reference to `_gfortran_transfer_integer_write'"
      ldlibs: -lgfortran
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang
      cxx: /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: clang@10.0.1.2
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      cxxflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      fflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/tce/packages/xl/xl-2022.08.19/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.08.19/bin/xlC
      fc: /usr/tce/packages/xl/xl-2022.08.19/bin/xlf2003
      f77: /usr/tce/packages/xl/xl-2022.08.19/bin/xlf
    spec: xl@16.1.1.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      cxxflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      fflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.2.0/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.2.0/bin/xlC
      fc: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.2.0/bin/xlf2003
      f77: /usr/tce/packages/xl/xl-2022.08.19-cuda-11.2.0/bin/xlf
    spec: xl@16.1.1.2
    target: ppc64le
