compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: gcc@8.3.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang
      cxx: /usr/tce/packages/clang/clang-ibm-10.0.1-gcc-8.3.1/bin/clang++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    spec: clang@10.0.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/tce/packages/xl/xl-2020.08.24-cuda-11.0.2/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2020.08.24-cuda-11.0.2/bin/xlC
      fc: /usr/tce/packages/xl/xl-2020.08.24-cuda-11.0.2/bin/xlf2003
      f77: /usr/tce/packages/xl/xl-2020.08.24-cuda-11.0.2/bin/xlf
    spec: xl@16.1.1.11
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/tce/packages/xl/xl-2022.03.10/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2022.03.10/bin/xlC
      fc: /usr/tce/packages/xl/xl-2021.12.22/bin/xlf2003
      f77: /usr/tce/packages/xl/xl-2021.12.22/bin/xlf
    spec: xl@16.1.1.12
    target: ppc64le
